### ISSUE TITLE
operationName is null

### ISSUE THREAD

**Issue by EQuimper** [AdamYee/apollo-link-redux#3]
Hello, thank you for this library. I get something weird for my app. When I get `APOLLO_QUERY_RESULT` or any other action, I don't get any operationName. But everything else is there.

<img width="512" alt="screen shot 2018-02-03 at 5 10 18 pm" src="https://user-images.githubusercontent.com/15819498/35772046-4c174294-0905-11e8-8578-ead974bf156a.png">

**Comment by AdamYee** [comment]
Hi @EQuimper 👋 

Can you provide the following:
`apollo-link` installed version?
`apollo-utilities` installed version?
`graphql` installed version?

If possible, can you debug the index.js file at this line https://github.com/AdamYee/apollo-link-redux/blob/master/src/index.js#L82 and tell me what keys/values you see in `operation`?

I'm not seeing the issue on my end, so I'm going to write a unit test. Once you let me know the versions of the above dependencies, I'll try to reproduce against the unit test.

**Comment by EQuimper** [comment]
Thank you for your response :)

```
		"@appandflow/masonry-list": "^0.4.0",
		"@appandflow/touchable": "^1.2.2",
		"apollo-cache-inmemory": "^1.1.2",
		"apollo-client": "^2.1.0",
		"apollo-link-context": "^1.0.2",
		"apollo-link-http": "^1.3.0",
		"apollo-link-logger": "^1.2.0",
		"apollo-link-redux": "^0.2.0",
		"apollo-link-state": "^0.3.1",
		"date-fns": "^1.29.0",
		"graphql": "^0.11.7",
		"graphql-tag": "^2.5.0",
		"lodash": "^4.17.4",
		"react": "16.0.0",
		"react-apollo": "^2.1.0-beta.0",
		"react-native": "0.51.0",
		"react-native-dialogs": "^0.0.21",
		"react-native-fast-image": "^2.2.4",
		"react-native-fbsdk": "^0.6.3",
		"react-native-keyboard-aware-scroll-view": "^0.4.1",
		"react-native-navigation": "^1.1.298",
		"react-native-typography": "^1.0.1",
		"react-native-vector-icons": "^4.4.2",
		"react-redux": "^5.0.6",
		"redux": "^3.7.2",
		"redux-thunk": "^2.2.0"
```

Umh I need apollo-utilities ? O you mean apollo-client ?

**Comment by AdamYee** [comment]
Ah, do you have `apollo-link` installed? It's a peer dependency of `apollo-link-redux`. I should update the docs to install this package with peer dependencies:

```
npm i -S apollo-link-redux apollo-link graphql
```

Make sure you have `apollo-link` installed. However, `apollo-utilities` will get installed automatically with this package because it's a direct dependency.

Thank you for showing me the versions in your package.json. You might want to lock down your versions by removing the `^` so we know exactly which package versions you've got installed.

**Comment by EQuimper** [comment]
Thank you, I change like you say but still get problem. I have `apollo-link@1.0.7`

**Comment by AdamYee** [comment]
I noticed you're using other links. You can try disabling them one at a time to see if a different link in your chain is mutating the operation. Might be hard for you to test depending on your app, but try disabling `apollo-link-context`, `apollo-link-logger`, or `apollo-link-state` and see if the `operationName` has a value in the dispatched actions.

**Comment by AdamYee** [comment]
Hi @EQuimper, I released patch version [0.2.1](https://github.com/AdamYee/apollo-link-redux/releases/tag/0.2.1) with a unit test for `operationName`.

I tested my theory about an upstream link mutating `operation`, but couldn't reproduce your issue. I think the only way to know for sure what is happening is to debug the code. If you like, you can DM me in Apollo's slack (@adamjyee) and we can continue the conversation there and debug your code.

**Comment by AdamYee** [comment]
Haha, I forgot to ask...does your query have an `operationName`? That could be the reason why.

Here's an example without
```
query {
    stub {
        id
    }
}
```

Here's an example with:
```
query SampleQuery {
    stub {
        id
    }
}
```

`SampleQuery` being the `operationName`. Can you confirm you've got one in the query?

**Comment by EQuimper** [comment]
Ok perfect I make it work with the name like you show :) Didn't think of it haha :) Sorry about that. Thank you for this lib :) Im using it for a tutorial Im building so :) Thank you
